item-app  | 
item-app  | 
item-app  | > docker-software-delivery@1.0.0 start /app
item-app  | > node ./bin/www
item-app  | 
item-app  | 
item-app  | NODE_ENV: production
item-app  | /app/node_modules/mongodb/lib/mongo_client.js:421
item-app  |           throw err
item-app  |           ^
item-app  | 
item-app  | 
item-app  | AssertionError [ERR_ASSERTION]: null == Error [MongoError]: failed to connect to server [item-db:27017] on first connect [Error: connect ECONNREFUSED 172.23.0.2:27017
item-app  |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
item-app  |   name: 'MongoError'
item-app  | }]
item-app  |     at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:336:35)
item-app  |     at Pool.emit (events.js:400:28)
item-app  |     at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:280:12)
item-app  |     at Object.onceWrapper (events.js:520:26)
item-app  |     at Connection.emit (e...
item-app  |     at /app/app.js:24:10
item-app  |     at connectCallback (/app/node_modules/mongodb/lib/mongo_client.js:527:5)
item-app  |     at /app/node_modules/mongodb/lib/mongo_client.js:418:11
item-app  |     at processTicksAndRejections (internal/process/task_queues.js:77:11) {
item-app  |   generatedMessage: true,
item-app  |   code: 'ERR_ASSERTION',
item-app  |   actual: null,
item-app  |   expected: Error [MongoError]: failed to connect to server [item-db:27017] on first connect [Error: connect ECONNREFUSED 172.23.0.2:27017
item-app  |       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
item-app  |     name: 'MongoError'
item-app  |   }]
item-app  |       at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:336:35)
item-app  |       at Pool.emit (events.js:400:28)
item-app  |       at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:280:12)
item-app  |       at Object.onceWrapper (events.js:520:26)
item-app  |       at Connection.emit (events.js:400:28)
item-app  |       at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:189:49)
item-app  |       at Object.onceWrapper (events.js:520:26)
item-app  |       at Socket.emit (events.js:400:28)
item-app  |       at emitErrorNT (internal/streams/destroy.js:106:8)
item-app  |       at emitErrorCloseNT (internal/streams/destroy.js:74:3),
item-app  |   operator: '=='
item-app  | }
item-app  | npm ERR! code ELIFECYCLE
item-app  | npm ERR! errno 1
item-app  | npm ERR! docker-software-delivery@1.0.0 start: `node ./bin/www`
item-app  | npm ERR! Exit status 1
item-app  | npm ERR! 
item-app  | npm ERR! Failed at the docker-software-delivery@1.0.0 start script.
item-app  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
item-app  | 
item-app  | 
item-app  | npm ERR! A complete log of this run can be found in:
item-app  | npm ERR!     /root/.npm/_logs/2023-08-20T04_50_38_385Z-debug.log
item-app  | 
item-app  | 
item-app  | > docker-software-delivery@1.0.0 start /app
item-app  | > node ./bin/www
item-app  | 
item-app  | 
item-app  | NODE_ENV: production
item-app  | Connected to database
item-app  | [0mGET / [32m200 [0m368.260 ms - 785[0m
item-app  | [0mGET /api [36m304 [0m54.389 ms - -[0m
item-app  | [0mGET / [32m200 [0m1.329 ms - 785[0m
item-app  | [0mGET /api [36m304 [0m3.708 ms - -[0m
item-app  | [0mGET / [32m200 [0m1.249 ms - 785[0m
item-app  | [0mGET /api [36m304 [0m3.062 ms - -[0m
item-app  | [0mGET / [32m200 [0m1.501 ms - 785[0m
item-app  | [0mGET /api [36m304 [0m2.993 ms - -[0m
item-app  | [0mPOST /api [32m201 [0m20.953 ms - 59[0m
item-db   | 2023-08-20T04:50:35.716+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=76ac128be03d
item-db   | 2023-08-20T04:50:35.716+0000 I CONTROL  [initandlisten] db version v3.6.23
item-db   | 2023-08-20T04:50:35.716+0000 I CONTROL  [initandlisten] git version: d352e6a4764659e0d0350ce77279de3c1f243e5c
item-db   | 2023-08-20T04:50:35.716+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
item-db   | 2023-08-20T04:50:35.716+0000 I CONTROL  [initandlisten] allocator: tcmalloc
item-db   | 2023-08-20T04:50:35.716+0000 I CONTROL  [initandlisten] modules: none
item-db   | 2023-08-20T04:50:35.716+0000 I CONTROL  [initandlisten] build environment:
item-db   | 2023-08-20T04:50:35.716+0000 I CONTROL  [initandlisten]     distmod: ubuntu1604
item-db   | 2023-08-20T04:50:35.716+0000 I CONTROL  [initandlisten]     distarch: x86_64
item-db   | 2023-08-20T04:50:35.716+0000 I CONTROL  [initandlisten]     target_arch: x86_64
item-db   | 2023-08-20T04:50:35.716+0000 I CONTROL  [initandlisten] options: { net: { bindIpAll: true } }
item-db   | 2023-08-20T04:50:35.726+0000 I -        [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
item-db   | 2023-08-20T04:50:35.726+0000 I STORAGE  [initandlisten] 
item-db   | 2023-08-20T04:50:35.726+0000 I STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
item-db   | 2023-08-20T04:50:35.726+0000 I STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
item-db   | 2023-08-20T04:50:35.727+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=469M,cache_overflow=(file_max=0M),session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),compatibility=(release="3.0",require_max="3.0"),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),
item-db   | 2023-08-20T04:50:37.142+0000 I STORAGE  [initandlisten] WiredTiger message [1692507037:142208][1:0x7f168e01aa40], txn-recover: Main recovery loop: starting at 1/28288
item-db   | 2023-08-20T04:50:37.314+0000 I STORAGE  [initandlisten] WiredTiger message [1692507037:314969][1:0x7f168e01aa40], txn-recover: Recovering log 1 through 2
item-db   | 2023-08-20T04:50:37.493+0000 I STORAGE  [initandlisten] WiredTiger message [1692507037:493466][1:0x7f168e01aa40], txn-recover: Recovering log 2 through 2
item-db   | 2023-08-20T04:50:37.653+0000 I STORAGE  [initandlisten] WiredTiger message [1692507037:653063][1:0x7f168e01aa40], txn-recover: Set global recovery timestamp: 0
item-db   | 2023-08-20T04:50:38.414+0000 I CONTROL  [initandlisten] 
item-db   | 2023-08-20T04:50:38.414+0000 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
item-db   | 2023-08-20T04:50:38.414+0000 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
item-db   | 2023-08-20T04:50:38.414+0000 I CONTROL  [initandlisten] 
item-db   | 2023-08-20T04:50:38.446+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
item-db   | 2023-08-20T04:50:38.447+0000 I NETWORK  [initandlisten] listening via socket bound to 0.0.0.0
item-db   | 2023-08-20T04:50:38.447+0000 I NETWORK  [initandlisten] listening via socket bound to /tmp/mongodb-27017.sock
item-db   | 2023-08-20T04:50:38.447+0000 I NETWORK  [initandlisten] waiting for connections on port 27017
item-db   | 2023-08-20T04:50:43.559+0000 I NETWORK  [listener] connection accepted from 172.23.0.3:48462 #1 (1 connection now open)
item-db   | 2023-08-20T04:50:43.567+0000 I NETWORK  [conn1] received client metadata from 172.23.0.3:48462 conn1: { driver: { name: "nodejs", version: "2.2.36" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "5.15.0-79-generic" }, platform: "Node.js v14.21.3, LE, mongodb-core: 2.1.20" }
